services:
  #  yugabyte-db:
  #    image: yugabytedb/yugabyte:latest
  #    container_name: yugabyte-db
  #    ports:
  #      - "7001:7000"   # Master UI
  #      - "9001:9000"   # Tserver UI
  #      - "5433:5433"   # YSQL (Postgres API)
  #    environment:
  #      - 'POSTGRES_DB=yugabyte'
  #      - 'POSTGRES_USER=yugabyte'
  #      - 'POSTGRES_PASSWORD=yugabyte'
  #    # Start Yugabyte-DB with default user and database
  #    command: >
  #      bin/yugabyted start --daemon=false
  #    volumes:
  #      - yugabyte_data:/home/yugabyte/yb_data
  #      - ./init-schema:/docker-entrypoint-initdb.d:ro
  #    healthcheck:
  #      test: [ "CMD-SHELL", "/home/yugabyte/bin/ysqlsh -h $(hostname) -c 'SELECT 1;' || exit 1" ]
  #      interval: 45s
  #      timeout: 10s
  #      retries: 3
  #      start_period: 90s
  #    ## To login into YSQL: docker exec -it yugabyte-db bash -c '/home/yugabyte/bin/ysqlsh -h $(hostname)'
  #    ## To load schema via SQL scripts: docker exec -it yugabyte-db bash -c '/home/yugabyte/bin/ysqlsh -h $(hostname) -f /docker-entrypoint-initdb.d/*.sql'

  yugabyte-db:
    image: yugabytedb/yugabyte:latest
    container_name: yugabyte-db
    ports:
      - "7001:7000"   # Master UI
      - "9001:9000"   # Tserver UI
      - "5433:5433"   # YSQL (Postgres API)
      - "9042:9042"   # YCQL (Cassandra API)
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    command: |
      bash -c "
      # Create database and user as soon as database is up
      until [ -z "POSTGRES_USER" ] || PGPASSWORD=yugabyte /home/yugabyte/bin/ysqlsh -h $(hostname) -v ON_ERROR_STOP=1 \\
       -c \"CREATE DATABASE $${POSTGRES_DB:-$${POSTGRES_USER}};\" \\
       -c \"CREATE USER $${POSTGRES_USER} WITH PASSWORD '$${POSTGRES_PASSWORD}';\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH SUPERUSER;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH CREATEDB;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH CREATEROLE;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH REPLICATION;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH BYPASSRLS;\" \\
       -c \"GRANT ALL PRIVILEGES ON DATABASE $${POSTGRES_DB:-$${POSTGRES_USER}} TO $${POSTGRES_USER};\" \\
       2>/dev/null
       do
        echo \"Retrying database and superuser creation...\" ; sleep 2
       done &
      # Now start Yugabyte-DB
      bin/yugabyted start --daemon=false"
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
      - ./init-schema:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: |
        bash -c '
        # Connect to custom database and run a simple query
        PGPASSWORD=$${POSTGRES_PASSWORD} /home/yugabyte/bin/ysqlsh -h $(hostname) -p 5433 -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c "
        SELECT
          current_database() as database,
          current_user as user,
          version() as version;
        " >/dev/null 2>&1 || exit 1'
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 90s
    ## To login into YSQL: docker exec -it yugabyte-db bash -c 'PGPASSWORD=secret /home/yugabyte/bin/ysqlsh -h $(hostname) -U my_user -d my_db'
    ## To load schema via SQL scripts: docker exec -it yugabyte-db bash -c 'PGPASSWORD=secret /home/yugabyte/bin/ysqlsh -h $(hostname) -U my_user -d my_db -f /docker-entrypoint-initdb.d/*.sql'

volumes:
  yugabyte_data:
